name: Python Tests

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
        uses: actions/checkout@v2

        - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.12.x'

        - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest junitparser

        - name: Run tests with pytest
        run: |
            pytest --junitxml=report.xml

        - name: Parse test results
        run: python test_results.py
      